# Generated by Django 5.1.7 on 2025-03-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('posicao', models.CharField(max_length=50)),
                ('contato', models.CharField(max_length=100)),
                ('status', models.CharField(default='ativo', max_length=20)),
            ],
        ),
    ]
